<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <Description>A simple library for constructing parsers in C#.</Description>
    <PackageTags>parser parsers</PackageTags>
    <IsPackable>true</IsPackable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RewritePackageReadmeLinks>true</RewritePackageReadmeLinks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
